apiVersion: v1
kind: Pod
metadata:
  name: pod-1
  labels:
    purpose: "Pod-1"
spec:
  containers:
  - name: with-pod-affinity
    image: registry.k8s.io/pause:3.8

---

apiVersion: v1
kind: Pod
metadata:
  name: pod-2
  labels:
    purpose: "Pod2-affinity"
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: purpose
            operator: In
            values:
            - "pod-1"
        topologyKey: "kubernetes.io/hostname"
  containers:
  - name: with-pod-affinity
    image: registry.k8s.io/pause:3.8