apiVersion: v1
kind: Pod
metadata:
  name: pod-1
  labels:
    purpose: "Pod-1"
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: hardware
            operator: NotIn
            values:
            - gpu
  containers:
  - name: with-pod-affinity
    image: registry.k8s.io/pause:3.8
  tolerations:
  - key: "hardware"
    operator: "Equal"
    value: "gpu"
    effect: "NoSchedule"

---

apiVersion: v1
kind: Pod
metadata:
  name: pod-2
  labels:
    purpose: "Pod2-affinity"
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: purpose
            operator: In
            values:
            - "Pod-1"
        topologyKey: "kubernetes.io/hostname"
  containers:
  - name: with-pod-affinity
    image: registry.k8s.io/pause:3.8
  